<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_23_Pandas Intro.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## 🟩 Load and Display Last 5 Rows (1.23.1)

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('/content/data_jobs.csv')

In [9]:
df.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [8]:
df.tail(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
358714,Data Scientist,Data Scientist,Abu Dhabi - United Arab Emirates,via Recruit.net,Full-time,False,United Arab Emirates,2023-01-17 23:34:14,False,False,United Arab Emirates,NaN,NaN,NaN,Al Nahiya Group,"['azure', 'aws', 'sap']","{'analyst_tools': ['sap'], 'cloud': ['azure', ..."
358715,Business Analyst,Production Analyst,Mexico,via The Muse,Full-time,False,Mexico,2023-06-06 23:16:17,False,False,Mexico,NaN,NaN,NaN,Coca-Cola,['sap'],{'analyst_tools': ['sap']}
358716,Data Engineer,"Data Engineer, Ads","Da’an District, Taipei City, Taiwan",via 1111人力銀行,NaN,False,Taiwan,2023-01-11 23:35:29,True,False,Taiwan,NaN,NaN,NaN,狄卡科技股份有限公司(Dcard),"['python', 'mongodb', 'mongodb', 'postgresql',...","{'databases': ['mongodb', 'postgresql'], 'othe..."
358717,Senior Data Analyst,Senior Data Analyst,"Birmingham, UK",via Recruit.net,Part-time,False,United Kingdom,2023-06-25 23:51:34,True,False,United Kingdom,NaN,NaN,NaN,Colmore,"['sql', 'python', 'ssrs', 'power bi']","{'analyst_tools': ['ssrs', 'power bi'], 'progr..."
358718,Senior Data Engineer,Senior Data Engineer,Singapore,via Recruit.net,Full-time,False,Singapore,2023-09-03 23:32:56,False,False,Singapore,NaN,NaN,NaN,Anter,NaN,NaN

---

## 🟩 Select Job Location Column (1.23.2)

In [11]:
df.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills'],
      dtype='object')

In [13]:
df['job_location']

0                               Watertown, CT
1                Guadalajara, Jalisco, Mexico
2                             Berlin, Germany
3                             San Antonio, TX
4                              Washington, DC
                         ...
358714       Abu Dhabi - United Arab Emirates
358715                                 Mexico
358716    Da’an District, Taipei City, Taiwan
358717                         Birmingham, UK
358718                              Singapore
Name: job_location, Length: 358719, dtype: object

---

## 🟩 Select Search Location Column (1.23.3)

In [14]:
df['search_location']

0         Texas, United States
1                       Mexico
2                      Germany
3         Texas, United States
4                        Sudan
                  ...
358714    United Arab Emirates
358715                  Mexico
358716                  Taiwan
358717          United Kingdom
358718               Singapore
Name: search_location, Length: 358719, dtype: object

---

## 🟩 Select Job Title from 57th Row Element (1.23.4)

In [15]:
df.loc[57, 'job_title']

'Data Engineer'

Dataset info

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358719 entries, 0 to 358718
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        358719 non-null  object
 1   job_title              358719 non-null  object
 2   job_location           358352 non-null  object
 3   job_via                358716 non-null  object
 4   job_schedule_type      353031 non-null  object
 5   job_work_from_home     358719 non-null  bool
 6   search_location        358719 non-null  object
 7   job_posted_date        358719 non-null  object
 8   job_no_degree_mention  358719 non-null  bool
 9   job_health_insurance   358719 non-null  bool
 10  job_country            358699 non-null  object
 11  salary_rate            13944 non-null   object
 12  salary_year_avg        9197 non-null    float64
 13  salary_hour_avg        4577 non-null    float64
 14  company_name           358713 non-null  object
 15  job_skills             302643 non-null  object
 16  job_type_skills        302643 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 39.3+ MB

# Access Thrid Row

In [19]:
df.iloc[3:5]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

---

# 🟨 Unique Job Countries

In [21]:
df.job_country.unique()

array(['United States', 'Mexico', 'Germany', 'Sudan', 'Romania',
       'Denmark', 'Switzerland', 'France', 'Brazil', 'United Kingdom',
       'India', 'Poland', 'Belgium', 'Russia', 'Serbia', 'Singapore',
       'Costa Rica', 'Ireland', 'Italy', 'Malaysia', 'Canada', 'Uruguay',
       'Namibia', 'Estonia', 'Israel', 'Hungary', 'Austria',
       'Philippines', 'Egypt', 'Australia', 'Chile', 'Spain',
       'Netherlands', 'South Africa', 'Colombia', 'Hong Kong', 'Kuwait',
       'Finland', 'Luxembourg', 'China', 'Puerto Rico', 'Sweden',
       'Saudi Arabia', 'Argentina', 'Turkey', 'Panama', 'Nigeria',
       'New Zealand', 'Ukraine', 'Jordan', 'United Arab Emirates',
       'Armenia', 'Pakistan', 'Lesotho', 'Mauritius', 'Portugal',
       'Bahrain', 'Taiwan', "Côte d'Ivoire", 'U.S. Virgin Islands',
       'Réunion', 'Kazakhstan', 'Lithuania', 'Moldova', 'Belarus',
       'Cyprus', 'Bulgaria', 'Honduras', 'Czechia', 'Peru', 'South Korea',
       'Malta', 'Indonesia', 'Tunisia', 'Latvia', 'Slovakia', 'Lebanon',
       'Japan', 'Sri Lanka', 'Slovenia', 'Bangladesh', 'Greece',
       'Ecuador', 'Oman', 'Kenya', 'Guyana', 'Vietnam', 'Norway',
       'Senegal', 'El Salvador', 'Iceland', 'Thailand', 'Ghana',
       'Croatia', 'Myanmar', 'Nepal', 'Morocco', 'Guadeloupe', 'Iraq',
       'Palestine', 'Guinea', 'Albania', 'Guatemala', 'Qatar', 'Uganda',
       'Bolivia', nan, 'Dominican Republic', 'Ethiopia', 'Haiti',
       'Uzbekistan', 'Bahamas', 'Liberia', 'Montenegro', 'Cayman Islands',
       'Mongolia', 'Macedonia (FYROM)', 'Azerbaijan', 'Burkina Faso',
       'Guam', 'Trinidad and Tobago', 'Benin', 'Kyrgyzstan',
       'Bosnia and Herzegovina', 'Zambia', 'Cameroon', 'Venezuela',
       'Barbados', 'Togo', 'Rwanda', 'Cambodia', 'Algeria', 'Afghanistan',
       'Congo, Democratic Republic of the', 'Zimbabwe', 'Jamaica',
       'Suriname', 'Mozambique', 'Yemen', 'Tanzania', 'Madagascar',
       'Mali', 'Paraguay', 'Brunei', 'Malawi', 'Nicaragua', 'Libya',
       'Tajikistan', 'Mauritania', 'Botswana', 'Fiji',
       'Northern Mariana Islands', 'Angola', 'Somalia',
       'Papua New Guinea', 'Gambia', 'Djibouti', 'Laos', 'Curaçao',
       'Maldives'], dtype=object)

In [22]:
missing_values_count = df.isnull().sum()
missing_values_df = pd.DataFrame(missing_values_count, columns=['missing_count'])
missing_values_df = missing_values_df.sort_values(by='missing_count', ascending=False)
display(missing_values_df[missing_values_df['missing_count'] > 0])

                   missing_count
salary_hour_avg           354142
salary_year_avg           349522
salary_rate               344775
job_type_skills            56076
job_skills                 56076
job_schedule_type           5688
job_location                 367
job_country                   20
company_name                   6
job_via                        3

# 🟨 Filter by Job Schedule Type and Display

In [23]:
df.count()

job_title_short          358719
job_title                358719
job_location             358352
job_via                  358716
job_schedule_type        353031
job_work_from_home       358719
search_location          358719
job_posted_date          358719
job_no_degree_mention    358719
job_health_insurance     358719
job_country              358699
salary_rate               13944
salary_year_avg            9197
salary_hour_avg            4577
company_name             358713
job_skills               302643
job_type_skills          302643
dtype: int64