<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_23_Pandas Intro.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# pandas intro

*   Pandas is a Python library used for working with data sets.
*   It lets us analyze, clean, explore and manipulate data.

In [1]:
# !conda install pandas

import pandas as pd

In [2]:
from datasets import load_dataset

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

data_jobs.csv:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

## 🟩 Load and Display Last 5 Rows (1.23.1)

In [4]:
df.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [5]:
df.tail(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785731,Data Engineer,Data Engineer,"Overland Park, Kansas, Amerika Serikat",melalui LinkedIn,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:17,False,False,Sudan,None,NaN,NaN,Shamrock Trading Corporation,"['nosql', 'mongodb', 'mongodb', 'python', 'ela...","{'analyst_tools': ['excel'], 'cloud': ['aws', ..."
785732,Data Engineer,Data Engineer (f/m/d),"Heidelberg, Jerman",melalui Top County Careers,Pekerjaan tetap,False,Germany,2023-03-13 06:18:59,False,False,Germany,None,NaN,NaN,Heidelberg Materials,"['python', 'c#', 'java', 'scala', 'sql', 'post...","{'cloud': ['azure', 'databricks'], 'databases'..."
785733,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:17,False,False,Singapore,None,NaN,NaN,Hydra X Pte. Ltd.,"['docker', 'kubernetes']","{'other': ['docker', 'kubernetes']}"
785734,Business Analyst,PreSales Engineer,"Almaty, Kazakhstan",melalui Melga,Pekerjaan tetap,False,Kazakhstan,2023-03-12 06:31:13,False,False,Kazakhstan,None,NaN,NaN,Staff-UP Consulting Group,['windows'],{'os': ['windows']}
785735,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",melalui Top County Careers,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,None,NaN,NaN,Pure App,"['sql', 'python', 'bigquery', 'aws', 'airflow'...","{'cloud': ['bigquery', 'aws'], 'libraries': ['..."
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [13]:
df['job_title_short']

0         Senior Data Engineer
1                 Data Analyst
2                Data Engineer
3                Data Engineer
4                Data Engineer
                  ...
785736       Software Engineer
785737            Data Analyst
785738        Business Analyst
785739           Data Engineer
785740       Software Engineer
Name: job_title_short, Length: 785741, dtype: object

In [14]:
df.job_title_short

0         Senior Data Engineer
1                 Data Analyst
2                Data Engineer
3                Data Engineer
4                Data Engineer
                  ...
785736       Software Engineer
785737            Data Analyst
785738        Business Analyst
785739           Data Engineer
785740       Software Engineer
Name: job_title_short, Length: 785741, dtype: object

---

# View all columns

In [7]:
df.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills'],
      dtype='object')

## 🟩 Select Job Location Column (1.23.2)

In [10]:
df[['job_location', 'search_location']] #showing multiple columns

                               job_location       search_location
0                             Watertown, CT  Texas, United States
1              Guadalajara, Jalisco, Mexico                Mexico
2                           Berlin, Germany               Germany
3                           San Antonio, TX  Texas, United States
4                            Washington, DC                 Sudan
...                                     ...                   ...
785736                            Singapura             Singapore
785737                   Bad Rodach, Jerman               Germany
785738                             Malaysia              Malaysia
785739  Newark, New Jersey, Amerika Serikat                 Sudan
785740                                India                 India

[785741 rows x 2 columns]

---

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

---

In [12]:
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

## 🟩 Pandas Inspection

In [15]:
df['job_title_short'].unique() # for unique values

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [16]:
len(df) # - Get length of DataFrame

785741

In [17]:
df.shape # - Get the (rows, columns)

(785741, 17)

In [18]:
df.index # - Describe index

RangeIndex(start=0, stop=785741, step=1)

In [19]:
df.columns # - Describe DataFrame columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills'],
      dtype='object')

In [26]:
df.count() # - Number of non-NA values

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

In [28]:
df[['job_title_short','job_title']].count() # - Number of non-NA values

job_title_short    785741
job_title          785740
dtype: int64

---

In [21]:
df.iloc[1] #to locate the row

job_title_short                                               Data Analyst
job_title                                                     Data Analyst
job_location                                  Guadalajara, Jalisco, Mexico
job_via                                                   via BeBee México
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Mexico
job_posted_date                                        2023-01-14 13:18:07
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                         Mexico
salary_rate                                                           None
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                    Hewlett Packard Enterprise
job_skills               ['r', 'python', 'sql', 'nosql', 'power bi', 't...
job_type_skills          {'analyst_tools': ['power bi', 'tableau'], 'pr...
Name: 1, dtype: object

In [22]:
df.iloc[1:10] #to locate multiple row

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,None,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

# Filtering Rows

Example:
Let's only return rows that have an salary_year_avg greater than 100000.

In [30]:
df[df['salary_year_avg'] > 100000]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
116,Data Scientist,Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-10-04 13:04:23,False,False,United States,year,114000.0,NaN,4 Corner Resources,"['r', 'python', 'sql', 't-sql', 'hadoop', 'spa...","{'analyst_tools': ['tableau'], 'libraries': ['..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [31]:
#What if I only wanted to look at rows where the job title (job_title_short) is 'Business Analyst'?
df[df['job_title_short'] == 'Business Analyst']

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
60,Business Analyst,Business Intelligence Intern,"Dallas, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-04 13:02:07,False,False,United States,None,NaN,NaN,Copart,"['r', 'python', 'sql', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
66,Business Analyst,BI Engineer,Namibia,via Intellijobs.ai,Full-time,False,Namibia,2023-03-05 14:10:49,False,False,Namibia,None,NaN,NaN,Innover,"['sql', 'gcp', 'looker', 'tableau']","{'analyst_tools': ['looker', 'tableau'], 'clou..."
71,Business Analyst,Business Analyst,"Tel Aviv-Yafo, Israel",via Comeet,Full-time,False,Israel,2023-09-05 13:50:12,False,False,Israel,None,NaN,NaN,ironSource,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
138,Business Analyst,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02-14 13:36:23,True,False,South Africa,None,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785720,Business Analyst,Senior Sales Engineer,"Jenewa, Swiss",melalui BeBee Schweiz,Pekerjaan tetap,False,Switzerland,2023-03-12 06:37:25,False,False,Switzerland,None,NaN,NaN,Snowflake,"['sql', 'snowflake', 'excel']","{'analyst_tools': ['excel'], 'cloud': ['snowfl..."
785721,Business Analyst,IT Business Analyst Data,Jerman,melalui Indeed,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,Raisin,"['sql', 'python', 'aws', 'looker', 'tableau', ...","{'analyst_tools': ['looker', 'tableau', 'splun..."
785722,Business Analyst,Business Analytics Training and Internship,Jerman,melalui LinkedIn,None,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,OESON,['python'],{'programming': ['python']}
785734,Business Analyst,PreSales Engineer,"Almaty, Kazakhstan",melalui Melga,Pekerjaan tetap,False,Kazakhstan,2023-03-12 06:31:13,False,False,Kazakhstan,None,NaN,NaN,Staff-UP Consulting Group,['windows'],{'os': ['windows']}
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"

**Finding Not null values**

Let's only get rows where it has a yearly salary listed. Meaning that salary_year_avg is not null.

In [32]:
df[df['salary_year_avg'].notna()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [34]:
df[df.salary_year_avg.notnull()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

You can apply this to multiple columns as well. Only return rows where the columns: salary_year_avg and job_skills are not null.

In [37]:
df[df[['salary_year_avg', 'job_skills']].notna().all(axis=1)]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785563,Data Scientist,Data Scientist I/II (Model Risk Management & M...,"Pensacola, FL",via Navy Federal Credit Union - Talentify,Full-time,False,"Florida, United States",2023-01-11 06:22:10,False,False,United States,year,136400.0,NaN,Navy Federal Credit Union,"['r', 'python', 'matplotlib', 'ggplot2', 'spar...","{'analyst_tools': ['word', 'power bi', 'tablea..."
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [38]:
df[df['salary_year_avg'].notna() & df['job_skills'].notna()]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785563,Data Scientist,Data Scientist I/II (Model Risk Management & M...,"Pensacola, FL",via Navy Federal Credit Union - Talentify,Full-time,False,"Florida, United States",2023-01-11 06:22:10,False,False,United States,year,136400.0,NaN,Navy Federal Credit Union,"['r', 'python', 'matplotlib', 'ggplot2', 'spar...","{'analyst_tools': ['word', 'power bi', 'tablea..."
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [39]:
df.notna()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,False,False
1,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785737,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785738,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785739,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True
785740,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True

#Pandas Cleaning

### Datetime

#### Notes

* `pd.to_datetime()`: Convert argument to datetime.

#### Example

In our DataFrame the `job_posted_date` is actually a string not a datetime format. First let's convert it to datetime format.

We'll also use `info()` to check if the data type changed from a string to a `datetime` format.

In [40]:
type(df['job_posted_date'][0])

str

In [48]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [52]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

### Date

#### Notes

* `dt`: accessor that provides a way to access specialized methods and properties we use to work with datatime data within a pandas series.
* `date`: extract the date component from the datetime object in the series.
* Use together `dt.date` on our series.

#### Example

Now let's turn it from a datetime to a date using `dt.date`.

In [56]:
df['job_posted_date'] = df['job_posted_date'].dt.date
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [57]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

## Sorting Values

### Notes

* `sort_values()` sorts a DataFrame or a specific column in ascending or descending order based on one or more columns.
* Typically this is used to sort by a specific column/s.
* Parameters:
    * `by` - column name or list of column names to sort by
    * `ascending` - boolean or list of booleans, default `True`, to sort by descending you would use `False`
    * `inplace` - whether to modify the DataFrame in place or return a new one

### Example

Let's sort our DataFrame by the `job_posted_date` in descending order (from most recent date to least).

In [59]:
df.sort_values(by='job_posted_date', ascending=False, inplace=True)
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
287457,Senior Data Engineer,Senior Data Engineer,"Randburg, South Africa",via CareerJunction,Full-time,False,South Africa,2023-12-31,False,False,South Africa,None,NaN,NaN,DCV Sabenza IT and Recruitment,"['sql', 'python', 'databricks', 'azure', 'hado...","{'analyst_tools': ['ssrs', 'power bi', 'tablea..."
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,None,NaN,NaN,Nationale Vacaturebank,None,None
114666,Senior Data Engineer,Senior Data Engineer (Python),"Wichita Falls, TX",via LinkedIn,Full-time and Part-time,False,Georgia,2023-12-31,False,True,United States,None,NaN,NaN,ClickJobs.io,"['python', 'java', 'scala', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."
696752,Data Engineer,Senior Data Engineer II,"Orange, CA",via BeBee,Full-time,False,Sudan,2023-12-31,False,True,Sudan,None,NaN,NaN,MobilityWare,"['python', 'java', 'c#', 'sql', 'aws', 'snowfl...","{'cloud': ['aws', 'snowflake', 'gcp'], 'librar..."
83884,Software Engineer,SAP B1 Applications Analyst,Germany,via BeBee,Full-time,False,Germany,2023-12-31,True,False,Germany,None,NaN,NaN,Systems Accountants,"['sql', 'crystal', 'sap']","{'analyst_tools': ['sap'], 'programming': ['sq..."

## Adding a Column

### Notes

- If you want to create a column you'll need to use the `df['column_name']` syntax.

### Example

Here we are creating a new column called 'Is Data Analyst' and saying if the column `job_title_short` is equal to 'Data Analyst' then then return 1 if not, return 0. It does this by using `astype(int)`.

In [62]:
df.columns

Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills', 'Is Data Analyst'],
      dtype='object')

In [63]:
df.job_schedule_type

287457                  Full-time
646083                  Full-time
114666    Full-time and Part-time
696752                  Full-time
83884                   Full-time
                   ...
542527                  Full-time
137492                  Full-time
778984                  Full-time
707242                  Full-time
347766                  Full-time
Name: job_schedule_type, Length: 785741, dtype: object

In [64]:
df['Full_time_job'] = (df.job_schedule_type == 'Full-time').astype(int)

In [65]:
df['Full_time_job']

287457    1
646083    1
114666    0
696752    1
83884     1
         ..
542527    1
137492    1
778984    1
707242    1
347766    1
Name: Full_time_job, Length: 785741, dtype: int64

In [67]:
df[df['Full_time_job'] > 0].head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,Is Data Analyst,Full_time_job
287457,Senior Data Engineer,Senior Data Engineer,"Randburg, South Africa",via CareerJunction,Full-time,False,South Africa,2023-12-31,False,False,South Africa,None,NaN,NaN,DCV Sabenza IT and Recruitment,"['sql', 'python', 'databricks', 'azure', 'hado...","{'analyst_tools': ['ssrs', 'power bi', 'tablea...",0,1
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,None,NaN,NaN,Nationale Vacaturebank,None,None,0,1
696752,Data Engineer,Senior Data Engineer II,"Orange, CA",via BeBee,Full-time,False,Sudan,2023-12-31,False,True,Sudan,None,NaN,NaN,MobilityWare,"['python', 'java', 'c#', 'sql', 'aws', 'snowfl...","{'cloud': ['aws', 'snowflake', 'gcp'], 'librar...",0,1
83884,Software Engineer,SAP B1 Applications Analyst,Germany,via BeBee,Full-time,False,Germany,2023-12-31,True,False,Germany,None,NaN,NaN,Systems Accountants,"['sql', 'crystal', 'sap']","{'analyst_tools': ['sap'], 'programming': ['sq...",0,1
507726,Data Engineer,Data Engineer,France,via BeBee,Full-time,False,France,2023-12-31,True,False,France,None,NaN,NaN,Groupe BPCE,"['scala', 'c#', 'sql', 'hadoop', 'spark']","{'libraries': ['hadoop', 'spark'], 'programmin...",0,1

## Dropping Data

### Notes

* Use `drop()` if you want to drop (delete) either a column or row in your database.
* The syntax is:
    * Drop column: `df.drop('column_name, axis = 1)`
    * Drop row: `df.drop(index_name, axis = 0)`
* If you wanted to drop multiple rows you would have the syntax:
    * Drop multiple columns: `df.drop(['column_name1', 'column_name2'], axis=1)`
    * Drop multiple rows: `df.drop([index_name1, index_name2], axis=0)`

### Examples

Let's drop the column `'salary_hour_avg'`, this will have an axis of 1 (since we're dropping a column).

In [68]:
df.drop('salary_hour_avg', axis = 1)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,Is Data Analyst,Full_time_job
287457,Senior Data Engineer,Senior Data Engineer,"Randburg, South Africa",via CareerJunction,Full-time,False,South Africa,2023-12-31,False,False,South Africa,None,NaN,DCV Sabenza IT and Recruitment,"['sql', 'python', 'databricks', 'azure', 'hado...","{'analyst_tools': ['ssrs', 'power bi', 'tablea...",0,1
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,None,NaN,Nationale Vacaturebank,None,None,0,1
114666,Senior Data Engineer,Senior Data Engineer (Python),"Wichita Falls, TX",via LinkedIn,Full-time and Part-time,False,Georgia,2023-12-31,False,True,United States,None,NaN,ClickJobs.io,"['python', 'java', 'scala', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az...",0,0
696752,Data Engineer,Senior Data Engineer II,"Orange, CA",via BeBee,Full-time,False,Sudan,2023-12-31,False,True,Sudan,None,NaN,MobilityWare,"['python', 'java', 'c#', 'sql', 'aws', 'snowfl...","{'cloud': ['aws', 'snowflake', 'gcp'], 'librar...",0,1
83884,Software Engineer,SAP B1 Applications Analyst,Germany,via BeBee,Full-time,False,Germany,2023-12-31,True,False,Germany,None,NaN,Systems Accountants,"['sql', 'crystal', 'sap']","{'analyst_tools': ['sap'], 'programming': ['sq...",0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542527,Data Scientist,Data Science Consultant,"Taguig, Metro Manila, Philippines",via Trabajo.org,Full-time,False,Philippines,2023-01-01,False,False,Philippines,None,NaN,AIA,None,None,0,1
137492,Data Engineer,Data Engineer - Customer Insights,"Amsterdam, Netherlands",via Melga,Full-time,False,Netherlands,2023-01-01,False,False,Netherlands,None,NaN,Booking.com,"['java', 'scala', 'python', 'perl', 'sql', 'my...","{'databases': ['mysql', 'cassandra'], 'librari...",0,1
778984,Cloud Engineer,Configuration Management Analyst,"Dublin, Ireland",via Trabajo.org,Full-time,False,Ireland,2023-01-01,True,False,Ireland,None,NaN,Vantage Resources,None,None,0,1
707242,Software Engineer,Software Engineer,Finland,via Trabajo.org,Full-time,False,Finland,2023-01-01,False,False,Finland,None,NaN,Uber,"['c++', 'nosql', 'python', 'java', 'go', 'kafka']","{'libraries': ['kafka'], 'programming': ['c++'...",0,1
347766,Data Engineer,"Manager, Data Engineering, SMAI","Bengaluru, Karnataka, India",via Careers At Micron Technology,Full-time,False,India,2023-01-01,False,False,India,None,NaN,Micron Technology,"['python', 'snowflake', 'gcp', 'hadoop']","{'cloud': ['snowflake', 'gcp'], 'libraries': [...",0,1

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 287457 to 347766
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  Is Data Analyst        785741 non-null  int64
 18  Full_time_job          785741 non-null  int64
dtypes: bool(3), float64(2), int64(2), object(12)
memory usage: 104.2+ MB

In [70]:
df.drop('salary_hour_avg', axis = 1, inplace=True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 287457 to 347766
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
 16  Is Data Analyst        785741 non-null  int64
 17  Full_time_job          785741 non-null  int64
dtypes: bool(3), float64(1), int64(2), object(12)
memory usage: 98.2+ MB

## Remove NA

### Notes

* To remove rows that contain empty cells use `dropna()`.
* By default `dropna()` will return a *new* DataFrame, and won't change the original.

### Example

Let's cleanup our `salary_year_avg` column by removing the `NaN` values in this column.

In [74]:
df.salary_year_avg.head()

287457   NaN
646083   NaN
114666   NaN
696752   NaN
83884    NaN
Name: salary_year_avg, dtype: float64

In [75]:
df.dropna(subset=['salary_year_avg'], inplace=True)

In [76]:
df = df[df['salary_year_avg'].notna()]

In [77]:
df.salary_year_avg.head()

574802     95150.0
120858    144000.0
122037    137500.0
3448      140000.0
581356    135000.0
Name: salary_year_avg, dtype: float64

# Pandas Analysis

## Descriptive Statistics

### Describe()

#### Notes

For a basic overview we'll be using `describe()`.
* It gets the following (for columns with numeric data):
  * count
  * mean
  * std
  * min
  * max
* Great for getting a quick overview of the basic stats for the table.
* It automatically skips NaN values.

#### Example

Use `describe()` on our DataFrame.

In [78]:
df.describe()

       salary_year_avg  Is Data Analyst  Full_time_job
count     22003.000000     22003.000000   22003.000000
mean     123286.274072         0.247739       0.955233
std       48312.449482         0.431709       0.206796
min       15000.000000         0.000000       0.000000
25%       90000.000000         0.000000       1.000000
50%      115000.000000         0.000000       1.000000
75%      150000.000000         0.000000       1.000000
max      960000.000000         1.000000       1.000000

In [79]:
df['salary_year_avg'].describe() #for individual columns

count     22003.000000
mean     123286.274072
std       48312.449482
min       15000.000000
25%       90000.000000
50%      115000.000000
75%      150000.000000
max      960000.000000
Name: salary_year_avg, dtype: float64

### Common Data Analysis Methods

#### Notes

But there are other methods like:
* `df.sum()` - Sum of values
* `df.cumsum()` - Cummulative sum of values
* `df.min()`/`df.max()` - Minimum/maximum values
* `df.idxmin()`/`df.idxmax()` - Indexes of minimum/Maximum value
* `df.mean()` - Mean of values
* `df.median()` - Median of values
* `df.mode()` - Mode of the values
* `series.value_counts()` - Counts of unique values for a Series (aka a column)
    * Typically used for counting *unique occurrences* within a single column.
    * It's not applicable to an entire DataFrame without specifying a column.
* Depending on the method, you can apply it directly to a DataFrame or a Series.

#### Examples

Let's get the count of the values in each column within the entire DataFrame.

In [81]:
df['salary_year_avg'].mode()

0    90000.0
Name: salary_year_avg, dtype: float64

In [82]:
df['salary_year_avg'].median()

115000.0

In [83]:
df['salary_year_avg'].sum()

np.float64(2712667888.4023438)

In [84]:
df['salary_year_avg'].min()

15000.0

In [85]:
df['salary_year_avg'].max()

960000.0

In [89]:
df['salary_year_avg'].idxmax()

np.int64(554784)

In [92]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,Is Data Analyst,Full_time_job
574802,Senior Data Analyst,Senior Reporting Analyst,"Iowa City, IA",via Ladders,Full-time,False,"Illinois, United States",2023-12-31,False,True,United States,year,95150.0,CVS Health,"['sql', 't-sql', 'sql server', 'ssrs', 'tableau']","{'analyst_tools': ['ssrs', 'tableau'], 'databa...",0,1
120858,Data Analyst,Machine Learning Data Analyst,Anywhere,via Get.It,Full-time,True,"California, United States",2023-12-31,False,True,United States,year,144000.0,Get It Recruit - Information Technology,"['sql', 'python', 'matplotlib', 'tableau', 'po...","{'analyst_tools': ['tableau', 'power bi'], 'li...",1,1
122037,Data Scientist,"Data Scientist, Principal","Mid Florida, FL",via Ladders,Full-time,False,"Florida, United States",2023-12-31,False,True,United States,year,137500.0,"Blackbaud, Inc.","['python', 'r', 'databricks', 'azure']","{'cloud': ['databricks', 'azure'], 'programmin...",0,1
3448,Senior Data Engineer,Senior Python Developer for Data Engineering,"New York, NY",via LinkedIn,Full-time,False,Georgia,2023-12-31,True,False,United States,year,140000.0,Luxoft,"['python', 'sql']","{'programming': ['python', 'sql']}",0,1
581356,Senior Data Engineer,Senior Data Engineer,Anywhere,via Get.It,Full-time,True,"Florida, United States",2023-12-31,False,True,United States,year,135000.0,Get It Recruit - Information Technology,"['sql', 'python', 'snowflake', 'databricks', '...","{'cloud': ['snowflake', 'databricks', 'azure',...",0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47131,Data Analyst,HR Data Analyst,"Washington, DC",via Indeed,Full-time,False,"New York, United States",2023-01-01,True,True,United States,year,77500.0,CyberCoders,['sharepoint'],{'analyst_tools': ['sharepoint']},1,1
69156,Data Scientist,Staff Data Scientist,Anywhere,via Indeed,Full-time,True,"California, United States",2023-01-01,False,True,United States,year,202500.0,CyberCoders,"['python', 'java', 'scala', 'sql', 'aws', 'had...","{'cloud': ['aws'], 'libraries': ['hadoop', 'sp...",0,1
705374,Data Scientist,Data Science Manager,"Carnegie, PA",via Indeed,Full-time,False,Georgia,2023-01-01,False,True,United States,year,133500.0,VISIMO,"['python', 'numpy', 'pandas', 'scikit-learn', ...","{'libraries': ['numpy', 'pandas', 'scikit-lear...",0,1
449502,Data Engineer,Data Engineer,"Dearborn, MI",via Indeed,Contractor,False,"Illinois, United States",2023-01-01,False,False,United States,year,165000.0,"Stefanini, Inc","['sql', 'python', 'gcp', 'bigquery', 'spring',...","{'cloud': ['gcp', 'bigquery'], 'libraries': ['...",0,0
728461,Data Analyst,Data Analyst,California,via LinkedIn,Contractor,False,"California, United States",2023-01-01,False,False,United States,year,92500.0,Robert Half,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ...",1,0

### Groupby()

#### Notes

* Use `groupby` to group your DataFrame by the unique values in a specific column.
* Lets you perform aggregation (e.g. mean, sum) on the grouped data.
* Aggregations you can perform:
  * `mean()`: Computes the mean of the groups
  * `sum()`: Calculates the sum of the group values
  * `median()`: Finds the median of each group
  * `min()` and `max()`: Determine the minimum and maximum values within each group
  * Counts:
    * `count()`: Counts the number of non-NA/null entries in each group
    * `size()`: Returns the size of each group (including NA/null values)
  * `std()` and `var()`: Calculate the standard deviation and variance of groups
  * `first()` and `last()`: Get the first and last row of each group
  * `unique()`: Counts the number of unique non-NA/null values in each group

#### Examples

If we want to find the average yearly salary by `job_title_short`.

In [94]:
df.groupby('job_title_short')['salary_year_avg'].mean()

job_title_short
Business Analyst              91082.612833
Cloud Engineer               111268.453846
Data Analyst                  93841.907854
Data Engineer                130125.604250
Data Scientist               135988.837171
Machine Learning Engineer    126774.315972
Senior Data Analyst          113911.363665
Senior Data Engineer         145840.611624
Senior Data Scientist        154206.292996
Software Engineer            113393.760054
Name: salary_year_avg, dtype: float64

In [95]:
df.groupby('job_country')['salary_year_avg'].mean()

job_country
Albania        79472.500000
Algeria        44550.000000
Argentina     105212.343750
Armenia        78757.000000
Australia     118987.574324
                  ...
Uruguay        69333.333333
Uzbekistan     30750.000000
Vietnam        90927.236364
Zambia         90670.000000
Zimbabwe       67056.666667
Name: salary_year_avg, Length: 108, dtype: float64

### Agg()

#### Notes

* `agg()` lets you apply multiple functions at once.
* You can pass a list of functions to `agg()` to apply them all to the grouped data, or a dictionary to apply specific functions to specific columns.


#### Example

For each job title (`job_title_short`) let's get the minimum and maximum values for the salary.

In [96]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max'])

                               min       max
job_title_short
Business Analyst           16500.0  387460.0
Cloud Engineer             42000.0  280000.0
Data Analyst               25000.0  650000.0
Data Engineer              15000.0  525000.0
Data Scientist             27000.0  960000.0
Machine Learning Engineer  30000.0  325000.0
Senior Data Analyst        30000.0  425000.0
Senior Data Engineer       35000.0  425000.0
Senior Data Scientist      45000.0  890000.0
Software Engineer          28000.0  375000.0